#ifndef LARK_MLC_MLC_LEX_H
#define LARK_MLC_MLC_LEX_H
/*
 * Copyright (c) 2009-2022 Michael P. Touloumtzis.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdio.h>

#include <util/bytebuf.h>

struct scanner_state {
	void *flexstate;
	struct bytebuf strbuf;
};

/* signatures of wrapper/helper functions (not autogenerated) */
extern void mlc_scan_init(struct scanner_state *scanner);
extern void mlc_scan_fini(struct scanner_state *scanner);
extern void mlc_scan_string(const char *s, struct scanner_state *scanner);

typedef void *mlc_yyscan_t;	/* same as flex's yyscan_t */

/* signatures of flex-generated functions (arg is 'flexstate') */
extern void mlc_yyrestart(FILE *fin, mlc_yyscan_t scanner);

#endif /* LARK_MLC_MLC_LEX_H */
